name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install goimports
        run: go get golang.org/x/tools/cmd/goimports

      - name: Go imports
        run: goimports

      - name: Get dependencies
        run: go get -t .

      - name: Test
        run: make test
